export enum BookingSource {
  DIRECT = "DIRECT",
  BOOKING_COM = "BOOKING_COM",
  MAKEMYTRIP = "MAKEMYTRIP",
  GOIBIBO = "GOIBIBO",
  EXPEDIA = "EXPEDIA",
  OTHERS = "OTHERS",
}

export enum Priority {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  URGENT = "URGENT",
}

export enum TaskStatus {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum RoomStatus {
  CLEANING = "CLEANING",
  MAINTENANCE = "MAINTENANCE",
  OCCUPIED = "OCCUPIED",
  AVAILABLE = "AVAILABLE",
}

export enum RoomType {
  STANDARD = "STANDARD",
  DELUXE = "DELUXE",
  SUITE = "SUITE",
  PRESIDENTIAL = "PRESIDENTIAL",
}

export enum BookingStatus {
  CONFIRMED = "CONFIRMED",
  CHECKED_IN = "CHECKED_IN",
  CHECKED_OUT = "CHECKED_OUT",
  CANCELLED = "CANCELLED",
}

export enum UserRole {
  ADMIN = "ADMIN",
  MANAGER = "MANAGER",
  STAFF = "STAFF",
}

export enum PaymentStatus {
  PENDING = "PENDING",
  PARTIAL = "PARTIAL",
  COMPLETED = "COMPLETED",
  REFUNDED = "REFUNDED",
}

export enum ShiftStatus {
  SCHEDULED = "SCHEDULED",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}
